import streamlit as st
st.title('New family healthy dinner')
st.header('Breakfast:')
st.text('------------------')
st.text('Eggs with mushrooms, peppers, chicken and cheese with a dash of salt and pepper')
st.text('Orange juice')
st.text('Water')
st.text('Hashbrowns')
st.text('             ')
st.header('Lunch:')
st.text('------------')
st.text('Rice with lentil soup and sauteed veggies')
st.text('Apple juice')
st.text('Water')
st.text('Cheesecake')
st.text('             ')
st.header('Dinner:')
st.text('------------')
st.text('Rice with fish and salad')
st.text('Yogurt')
st.text('Water')

